# Generated by Django 4.0.4 on 2022-06-27 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total',
        ),
    ]
