from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(CategoryProduct)
admin.site.register(Product)
admin.site.register(Colours)
admin.site.register(Wishlist)
admin.site.register(Reviews)
admin.site.register(NewLetteer)
admin.site.register(ContactUs)
admin.site.register(Country)
admin.site.register(Address)
admin.site.register(Shippingaddress)
admin.site.register(Accounts)
admin.site.register(RestoreAccount)
admin.site.register(Tags)
admin.site.register(Blog)
admin.site.register(Blog_Comments)
admin.site.register(Cookies)
admin.site.register(Privacy_Policy)
admin.site.register(About)
admin.site.register(Coupons)
admin.site.register(Usedcoupons)
admin.site.register(Card)
admin.site.register(Order)